/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function login(username: string, password: string, clientExecPath: string) {
    return invoke()<null>("login", { username,password,clientExecPath })
}

export function checkExec(clientExecPath: string) {
    return invoke()<boolean>("check_exec", { clientExecPath })
}


